

export const ASL_CULTURE_QUOTES: string[] = [
    "American Sign Language is a language of vision, a language of movement, a language of space.",
    "The hands are the voice of the Deaf.",
    "Deafness is not a disability, but a culture.",
    "ASL is not a universal language, but it is a universal concept.",
    "In American Sign Language, the face is the grammar.",
    "To be deaf is not to be silent. It is to be a part of a vibrant, visual world.",
    "The Deaf community is not a silent world. It is a world full of visual noise.",
    "What matters is not whether you can hear, but whether you can understand.",
    "Through the hands, the heart speaks.",
    "ASL is a dance that is performed with the hands.",
    "Our hands are our tongues, our bodies are our language.",
    "Deaf culture is a celebration of life, language, and community.",
    "The first permanent school for the deaf in the U.S., now the American School for the Deaf, was founded in 1817.",
    "ASL grammar is completely different from English, with its own rules for phonology, morphology, and syntax.",
    "Gallaudet University, located in Washington, D.C., is the only university in the world specifically for Deaf and hard of hearing students.",
    "Many Deaf people consider themselves part of a cultural and linguistic minority, not as disabled individuals.",
    "A 'name sign' in Deaf culture is a unique sign given to a person, serving as their name within the community.",
    "Laurent Clerc, a Deaf man from France, co-founded the first school for the Deaf in the U.S.",
    "The 'Deaf President Now' (DPN) protest in 1988 was a pivotal moment for Deaf rights at Gallaudet University.",
    "Not all Deaf people use sign language; some use oral methods or Cued Speech.",
    "ASL is the third most common language in the United States, after English and Spanish.",
    "Facial expressions and body language in ASL are called 'non-manual markers' and are essential for grammar.",
    "The use of space in front of the signer (signing space) is crucial for conveying meaning in ASL.",
    "Fingerspelling is used for proper nouns like names, places, and brands that don't have a specific sign.",
    "ASL has regional variations and dialects, much like spoken languages.",
    "The 'I Love You' sign combines the handshapes for 'I', 'L', and 'Y' in the ASL alphabet.",
    "It's considered rude to break eye contact while someone is signing to you.",
    "To get a Deaf person's attention, you can tap them on the shoulder, wave your hand, or flick the lights.",
    "Deaf theater, such as the National Theatre of the Deaf, has a rich history of creating visually stunning performances.",
    "The TTY (teletypewriter) was a breakthrough device that allowed Deaf people to communicate over phone lines.",
    "Modern technology like video relay services (VRS) and smartphones has revolutionized communication for the Deaf community.",
    "The term 'Hearing-impaired' is often disliked by the Deaf community, who prefer 'Deaf' or 'hard of hearing'.",
    "In Deaf culture, being direct and straightforward in communication is highly valued.",
    "Storytelling is a cherished art form in Deaf culture, passed down through generations.",
    "The concept of 'Deaf Gain' reframes deafness not as a loss of hearing, but as a unique way of being and a gain for humanity.",
    "ASL is not based on English. It was developed from French Sign Language (LSF) and local sign languages.",
    "The rhythm and speed of signing can convey different emotions and nuances.",
    "When referring to a person who is not present, signers will point to a specific spot in space and refer back to it.",
    "Classifiers in ASL are handshapes used to represent nouns and their size, shape, or movement.",
    "A common misconception is that ASL is just a system of gestures; it is a complete and complex language.",
    "In Deaf culture, long goodbyes are common, with conversations often continuing long after the initial farewell.",
    "Applause in the Deaf community is done by waving hands in the air.",
    "Deaf-blind individuals use Tactile ASL, where the listener places their hands over the signer's to feel the signs.",
    "Many Deaf individuals enjoy music by feeling the vibrations.",
    "The Americans with Disabilities Act (ADA) of 1990 was a landmark law that mandated access for Deaf individuals, including interpreters.",
    "The cochlear implant is a controversial topic within the Deaf community, with varying perspectives on its use.",
    "There are over 300 different sign languages used around the world.",
    "ASL has its own poetry and literature, which utilizes the visual and spatial aspects of the language.",
    "The sign for 'America' is derived from the idea of a log cabin with interlocked fingers.",
    "Learning ASL can improve peripheral vision and reaction time."
];