import type { AlphabetSign, KanjiQuizQuestion, KanjiLevel } from './types';

// Template for alphabet signs.
// The image URLs have been updated to a reliable source.
export const ALPHABET: AlphabetSign[] = [
  { letter: 'A', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/a.gif' },
  { letter: 'B', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/b.gif' },
  { letter: 'C', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/c.gif' },
  { letter: 'D', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/d.gif' },
  { letter: 'E', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/e.gif' },
  { letter: 'F', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/f.gif' },
  { letter: 'G', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/g.gif' },
  { letter: 'H', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/h.gif' },
  { letter: 'I', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/i.gif' },
  { letter: 'J', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/j.gif' },
  { letter: 'K', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/k.gif' },
  { letter: 'L', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/l.gif' },
  { letter: 'M', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/m.gif' },
  { letter: 'N', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/n.gif' },
  { letter: 'O', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/o.gif' },
  { letter: 'P', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/p.gif' },
  { letter: 'Q', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/q.gif' },
  { letter: 'R', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/r.gif' },
  { letter: 'S', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/s.gif' },
  { letter: 'T', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/t.gif' },
  { letter: 'U', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/u.gif' },
  { letter: 'V', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/v.gif' },
  { letter: 'W', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/w.gif' },
  { letter: 'X', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/x.gif' },
  { letter: 'Y', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/y.gif' },
  { letter: 'Z', imageUrl: 'https://www.lifeprint.com/asl101/fingerspelling/abc-gifs/z.gif' },
];

export const JSL_ALPHABET: AlphabetSign[] = [
  { letter: 'あ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/A-jsl-yubimoji.png?width=300', romaji: 'a' },
  { letter: 'い', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/I-jsl-yubimoji.png?width=300', romaji: 'i' },
  { letter: 'う', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/U-jsl-yubimoji.png?width=300', romaji: 'u' },
  { letter: 'え', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/E-jsl-yubimoji.png?width=300', romaji: 'e' },
  { letter: 'お', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/O-jsl-yubimoji.png?width=300', romaji: 'o' },
  { letter: 'か', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ka-jsl-yubimoji.png?width=300', romaji: 'ka' },
  { letter: 'き', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ki-jsl-yubimoji.png?width=300', romaji: 'ki' },
  { letter: 'く', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ku-jsl-yubimoji.png?width=300', romaji: 'ku' },
  { letter: 'け', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ke-jsl-yubimoji.png?width=300', romaji: 'ke' },
  { letter: 'こ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ko-jsl-yubimoji.png?width=300', romaji: 'ko' },
  { letter: 'さ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sa-jsl-yubimoji.png?width=300', romaji: 'sa' },
  { letter: 'し', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Si-jsl-yubimoji.png?width=300', romaji: 'shi' },
  { letter: 'す', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Su-jsl-yubimoji.png?width=300', romaji: 'su' },
  { letter: 'せ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Se-jsl-yubimoji.png?width=300', romaji: 'se' },
  { letter: 'そ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/So-jsl-yubimoji.png?width=300', romaji: 'so' },
  { letter: 'た', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ta-jsl-yubimoji.png?width=300', romaji: 'ta' },
  { letter: 'ち', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ti-jsl-yubimoji.png?width=300', romaji: 'chi' },
  { letter: 'つ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Tu-jsl-yubimoji.png?width=300', romaji: 'tsu' },
  { letter: 'て', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Te-jsl-yubimoji.png?width=300', romaji: 'te' },
  { letter: 'と', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/To-jsl-yubimoji.png?width=300', romaji: 'to' },
  { letter: 'な', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Na-jsl-yubimoji.png?width=300', romaji: 'na' },
  { letter: 'に', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ni-jsl-yubimoji.png?width=300', romaji: 'ni' },
  { letter: 'ぬ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nu-jsl-yubimoji.png?width=300', romaji: 'nu' },
  { letter: 'ね', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ne-jsl-yubimoji.png?width=300', romaji: 'ne' },
  { letter: 'の', imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/5/56/NO-jsl-yubimoji.png?width=300', romaji: 'no' },
];

export const JSL_KATAKANA_ALPHABET: AlphabetSign[] = [
  { letter: 'ア', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/A-jsl-yubimoji.png?width=300', romaji: 'a' },
  { letter: 'イ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/I-jsl-yubimoji.png?width=300', romaji: 'i' },
  { letter: 'ウ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/U-jsl-yubimoji.png?width=300', romaji: 'u' },
  { letter: 'エ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/E-jsl-yubimoji.png?width=300', romaji: 'e' },
  { letter: 'オ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/O-jsl-yubimoji.png?width=300', romaji: 'o' },
  { letter: 'カ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ka-jsl-yubimoji.png?width=300', romaji: 'ka' },
  { letter: 'キ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ki-jsl-yubimoji.png?width=300', romaji: 'ki' },
  { letter: 'ク', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ku-jsl-yubimoji.png?width=300', romaji: 'ku' },
  { letter: 'ケ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ke-jsl-yubimoji.png?width=300', romaji: 'ke' },
  { letter: 'コ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ko-jsl-yubimoji.png?width=300', romaji: 'ko' },
  { letter: 'サ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Sa-jsl-yubimoji.png?width=300', romaji: 'sa' },
  { letter: 'シ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Si-jsl-yubimoji.png?width=300', romaji: 'shi' },
  { letter: 'ス', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Su-jsl-yubimoji.png?width=300', romaji: 'su' },
  { letter: 'セ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Se-jsl-yubimoji.png?width=300', romaji: 'se' },
  { letter: 'ソ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/So-jsl-yubimoji.png?width=300', romaji: 'so' },
  { letter: 'タ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ta-jsl-yubimoji.png?width=300', romaji: 'ta' },
  { letter: 'チ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ti-jsl-yubimoji.png?width=300', romaji: 'chi' },
  { letter: 'ツ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Tu-jsl-yubimoji.png?width=300', romaji: 'tsu' },
  { letter: 'テ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Te-jsl-yubimoji.png?width=300', romaji: 'te' },
  { letter: 'ト', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/To-jsl-yubimoji.png?width=300', romaji: 'to' },
  { letter: 'ナ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Na-jsl-yubimoji.png?width=300', romaji: 'na' },
  { letter: 'ニ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ni-jsl-yubimoji.png?width=300', romaji: 'ni' },
  { letter: 'ヌ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Nu-jsl-yubimoji.png?width=300', romaji: 'nu' },
  { letter: 'ネ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/Ne-jsl-yubimoji.png?width=300', romaji: 'ne' },
  { letter: 'ノ', imageUrl: 'https://commons.wikimedia.org/wiki/Special:Redirect/file/No-jsl-yubimoji.png?width=300', romaji: 'no' },
];

export const KANJI_QUIZ_DATA: Record<KanjiLevel, KanjiQuizQuestion[]> = {
    1: [
        { kanji: '一', meaning: 'One', romaji: 'ichi', distractors: ['Two', 'Ten', 'Hundred'] },
        { kanji: '二', meaning: 'Two', romaji: 'ni', distractors: ['One', 'Three', 'Four'] },
        { kanji: '三', meaning: 'Three', romaji: 'san', distractors: ['Two', 'Five', 'Six'] },
        { kanji: '四', meaning: 'Four', romaji: 'shi / yon', distractors: ['Five', 'Six', 'Seven'] },
        { kanji: '五', meaning: 'Five', romaji: 'go', distractors: ['Four', 'Ten', 'Zero'] },
        { kanji: '六', meaning: 'Six', romaji: 'roku', distractors: ['Seven', 'Eight', 'Nine'] },
        { kanji: '七', meaning: 'Seven', romaji: 'shichi / nana', distractors: ['Six', 'Eight', 'One'] },
        { kanji: '八', meaning: 'Eight', romaji: 'hachi', distractors: ['Nine', 'Ten', 'Seven'] },
        { kanji: '九', meaning: 'Nine', romaji: 'kyū / ku', distractors: ['Eight', 'Ten', 'Six'] },
        { kanji: '十', meaning: 'Ten', romaji: 'jū', distractors: ['Hundred', 'Thousand', 'One'] },
        { kanji: '人', meaning: 'Person', romaji: 'hito / jin', distractors: ['Animal', 'God', 'Child'] },
        { kanji: '日', meaning: 'Day / Sun', romaji: 'nichi / hi', distractors: ['Moon', 'Star', 'Night'] },
        { kanji: '月', meaning: 'Moon / Month', romaji: 'getsu / tsuki', distractors: ['Sun', 'Fire', 'Water'] },
        { kanji: '火', meaning: 'Fire', romaji: 'ka / hi', distractors: ['Water', 'Earth', 'Wind'] },
        { kanji: '水', meaning: 'Water', romaji: 'sui / mizu', distractors: ['Fire', 'Mountain', 'River'] },
        { kanji: '木', meaning: 'Tree / Wood', romaji: 'moku / ki', distractors: ['Flower', 'Grass', 'Forest'] },
        { kanji: '金', meaning: 'Gold / Money', romaji: 'kin', distractors: ['Silver', 'Bronze', 'Jewel'] },
        { kanji: '土', meaning: 'Earth / Soil', romaji: 'do / tsuchi', distractors: ['Sky', 'Sea', 'Stone'] },
        { kanji: '年', meaning: 'Year', romaji: 'nen / toshi', distractors: ['Month', 'Week', 'Day'] },
        { kanji: '時', meaning: 'Time / Hour', romaji: 'ji / toki', distractors: ['Day', 'Minute', 'Week'] },
    ],
    2: [
        { kanji: '分', meaning: 'Minute / Understand', romaji: 'fun / wakaru', distractors: ['Hour', 'Second', 'Time'] },
        { kanji: '行', meaning: 'Go', romaji: 'iku / gō', distractors: ['Come', 'Stop', 'Run'] },
        { kanji: '来', meaning: 'Come', romaji: 'kuru / rai', distractors: ['Go', 'Leave', 'Enter'] },
        { kanji: '見', meaning: 'See', romaji: 'miru', distractors: ['Hear', 'Touch', 'Smell'] },
        { kanji: '出', meaning: 'Exit', romaji: 'deru / dasu', distractors: ['Enter', 'Stay', 'Open'] },
        { kanji: '入', meaning: 'Enter', romaji: 'hairu / iru', distractors: ['Exit', 'Leave', 'Close'] },
        { kanji: '上', meaning: 'Up / Above', romaji: 'ue / jō', distractors: ['Down', 'Below', 'Inside'] },
        { kanji: '下', meaning: 'Down / Below', romaji: 'shita / ka', distractors: ['Up', 'Above', 'Outside'] },
        { kanji: '右', meaning: 'Right', romaji: 'migi', distractors: ['Left', 'Center', 'Straight'] },
        { kanji: '左', meaning: 'Left', romaji: 'hidari', distractors: ['Right', 'Center', 'Back'] },
        { kanji: '前', meaning: 'Before / Front', romaji: 'mae / zen', distractors: ['After', 'Back', 'Behind'] },
        { kanji: '後', meaning: 'After / Back', romaji: 'ato / go', distractors: ['Before', 'Front', 'Side'] },
        { kanji: '中', meaning: 'Middle / Inside', romaji: 'naka / chū', distractors: ['Outside', 'Edge', 'Top'] },
        { kanji: '外', meaning: 'Outside', romaji: 'soto / gai', distractors: ['Inside', 'Center', 'Core'] },
        { kanji: '東', meaning: 'East', romaji: 'higashi', distractors: ['West', 'North', 'South'] },
        { kanji: '西', meaning: 'West', romaji: 'nishi', distractors: ['East', 'North', 'South'] },
        { kanji: '南', meaning: 'South', romaji: 'minami', distractors: ['North', 'East', 'West'] },
        { kanji: '北', meaning: 'North', romaji: 'kita', distractors: ['South', 'East', 'West'] },
        { kanji: '名', meaning: 'Name', romaji: 'na', distractors: ['Word', 'Number', 'Place'] },
        { kanji: '円', meaning: 'Yen / Circle', romaji: 'en', distractors: ['Dollar', 'Square', 'Euro'] },
    ],
    3: [
        { kanji: '口', meaning: 'Mouth', romaji: 'kuchi', distractors: ['Nose', 'Eye', 'Ear'] },
        { kanji: '目', meaning: 'Eye', romaji: 'me', distractors: ['Mouth', 'Face', 'Look'] },
        { kanji: '耳', meaning: 'Ear', romaji: 'mimi', distractors: ['Nose', 'Eye', 'Head'] },
        { kanji: '手', meaning: 'Hand', romaji: 'te', distractors: ['Foot', 'Arm', 'Finger'] },
        { kanji: '足', meaning: 'Foot / Leg', romaji: 'ashi', distractors: ['Hand', 'Arm', 'Head'] },
        { kanji: '体', meaning: 'Body', romaji: 'karada', distractors: ['Mind', 'Soul', 'Spirit'] },
        { kanji: '力', meaning: 'Power / Strength', romaji: 'chikara', distractors: ['Weakness', 'Energy', 'Speed'] },
        { kanji: '心', meaning: 'Heart / Mind', romaji: 'kokoro', distractors: ['Body', 'Soul', 'Thought'] },
        { kanji: '父', meaning: 'Father', romaji: 'chichi', distractors: ['Mother', 'Brother', 'Son'] },
        { kanji: '母', meaning: 'Mother', romaji: 'haha', distractors: ['Father', 'Sister', 'Daughter'] },
        { kanji: '子', meaning: 'Child', romaji: 'ko', distractors: ['Adult', 'Parent', 'Baby'] },
        { kanji: '女', meaning: 'Woman', romaji: 'onna', distractors: ['Man', 'Girl', 'Boy'] },
        { kanji: '男', meaning: 'Man', romaji: 'otoko', distractors: ['Woman', 'Boy', 'Girl'] },
        { kanji: '先', meaning: 'Ahead / Previous', romaji: 'saki / sen', distractors: ['Behind', 'After', 'Next'] },
        { kanji: '生', meaning: 'Life / Birth', romaji: 'sei / umareru', distractors: ['Death', 'End', 'Old'] },
        { kanji: '学', meaning: 'Learn', romaji: 'gaku / manabu', distractors: ['Teach', 'Read', 'Write'] },
        { kanji: '校', meaning: 'School', romaji: 'kō', distractors: ['Home', 'Office', 'Library'] },
        { kanji: '友', meaning: 'Friend', romaji: 'tomo', distractors: ['Enemy', 'Family', 'Stranger'] },
        { kanji: '本', meaning: 'Book / Origin', romaji: 'hon', distractors: ['Paper', 'Pen', 'Magazine'] },
        { kanji: '毎', meaning: 'Every', romaji: 'mai', distractors: ['Some', 'None', 'Always'] },
    ],
    4: [
        { kanji: '何', meaning: 'What', romaji: 'nani / nan', distractors: ['Who', 'Where', 'When'] },
        { kanji: '言', meaning: 'Say', romaji: 'iu / koto', distractors: ['Ask', 'Listen', 'Tell'] },
        { kanji: '話', meaning: 'Speak / Talk', romaji: 'hanasu / wa', distractors: ['Listen', 'Read', 'Whisper'] },
        { kanji: '読', meaning: 'Read', romaji: 'yomu', distractors: ['Write', 'Listen', 'Speak'] },
        { kanji: '書', meaning: 'Write', romaji: 'kaku', distractors: ['Read', 'Draw', 'Type'] },
        { kanji: '聞', meaning: 'Hear / Listen', romaji: 'kiku', distractors: ['See', 'Say', 'Smell'] },
        { kanji: '食', meaning: 'Eat', romaji: 'taberu', distractors: ['Drink', 'Cook', 'Taste'] },
        { kanji: '飲', meaning: 'Drink', romaji: 'nomu', distractors: ['Eat', 'Spill', 'Pour'] },
        { kanji: '買', meaning: 'Buy', romaji: 'kau', distractors: ['Sell', 'Trade', 'Find'] },
        { kanji: '店', meaning: 'Shop', romaji: 'mise', distractors: ['House', 'Market', 'Office'] },
        { kanji: '駅', meaning: 'Station', romaji: 'eki', distractors: ['Airport', 'Bus Stop', 'Port'] },
        { kanji: '道', meaning: 'Road / Way', romaji: 'michi / dō', distractors: ['Path', 'River', 'Street'] },
        { kanji: '車', meaning: 'Car', romaji: 'kuruma / sha', distractors: ['Bicycle', 'Train', 'Bus'] },
        { kanji: '電', meaning: 'Electricity', romaji: 'den', distractors: ['Water', 'Gas', 'Light'] },
        { kanji: '語', meaning: 'Language / Word', romaji: 'go', distractors: ['Sentence', 'Letter', 'Sound'] },
        { kanji: '国', meaning: 'Country', romaji: 'kuni / koku', distractors: ['City', 'State', 'Continent'] },
        { kanji: '会', meaning: 'Meet', romaji: 'au / kai', distractors: ['Leave', 'Separate', 'Gather'] },
        { kanji: '社', meaning: 'Company', romaji: 'sha', distractors: ['Society', 'Group', 'Office'] },
        { kanji: '今', meaning: 'Now', romaji: 'ima', distractors: ['Later', 'Before', 'Today'] },
        { kanji: '週', meaning: 'Week', romaji: 'shū', distractors: ['Day', 'Month', 'Year'] },
    ],
    5: [
        { kanji: '天', meaning: 'Heaven / Sky', romaji: 'ten', distractors: ['Earth', 'Hell', 'Sea'] },
        { kanji: '気', meaning: 'Spirit / Air', romaji: 'ki', distractors: ['Energy', 'Weather', 'Feeling'] },
        { kanji: '雨', meaning: 'Rain', romaji: 'ame', distractors: ['Snow', 'Sun', 'Wind'] },
        { kanji: '雪', meaning: 'Snow', romaji: 'yuki', distractors: ['Rain', 'Ice', 'Hail'] },
        { kanji: '風', meaning: 'Wind', romaji: 'kaze', distractors: ['Breeze', 'Storm', 'Air'] },
        { kanji: '晴', meaning: 'Clear up', romaji: 'hareru', distractors: ['Cloudy', 'Rainy', 'Sunny'] },
        { kanji: '高', meaning: 'High / Expensive', romaji: 'takai', distractors: ['Low', 'Cheap', 'Short'] },
        { kanji: '安', meaning: 'Cheap / Peaceful', romaji: 'yasui', distractors: ['Expensive', 'Costly', 'High'] },
        { kanji: '大', meaning: 'Big / Large', romaji: 'ōkii / dai', distractors: ['Small', 'Little', 'Tiny'] },
        { kanji: '小', meaning: 'Small / Little', romaji: 'chiisai / shō', distractors: ['Big', 'Large', 'Huge'] },
        { kanji: '新', meaning: 'New', romaji: 'atarashii / shin', distractors: ['Old', 'Ancient', 'Used'] },
        { kanji: '古', meaning: 'Old', romaji: 'furui / ko', distractors: ['New', 'Modern', 'Young'] },
        { kanji: '多', meaning: 'Many / Much', romaji: 'ōi', distractors: ['Few', 'Some', 'Little'] },
        { kanji: '少', meaning: 'Few / Little', romaji: 'sukunai / sukoshi', distractors: ['Many', 'Much', 'A lot'] },
        { kanji: '長', meaning: 'Long', romaji: 'nagai', distractors: ['Short', 'Tall', 'Wide'] },
        { kanji: '短', meaning: 'Short', romaji: 'mijikai', distractors: ['Long', 'Tall', 'Narrow'] },
        { kanji: '好', meaning: 'Like / Good', romaji: 'suki / konomu', distractors: ['Dislike', 'Hate', 'Bad'] },
        { kanji: '白', meaning: 'White', romaji: 'shiro', distractors: ['Black', 'Red', 'Blue'] },
        { kanji: '黒', meaning: 'Black', romaji: 'kuro', distractors: ['White', 'Gray', 'Brown'] },
        { kanji: '赤', meaning: 'Red', romaji: 'aka', distractors: ['Blue', 'Green', 'Yellow'] },
    ]
};

export const FLUENCY_BASE_COST = 3;
export const FLUENCY_COST_MULTIPLIER = 1.4;

// Quotes about ASL and Deaf Culture
export const ASL_CULTURE_QUOTES: string[] = [
    "American Sign Language is a language of vision, a language of movement, a language of space.",
    "The hands are the voice of the Deaf.",
    "Deafness is not a disability, but a culture.",
    "ASL is not a universal language, but it is a universal concept.",
    "In American Sign Language, the face is the grammar.",
    "To be deaf is not to be silent. It is to be a part of a vibrant, visual world.",
    "The Deaf community is not a silent world. It is a world full of visual noise.",
    "What matters is not whether you can hear, but whether you can understand.",
    "Through the hands, the heart speaks.",
    "ASL is a dance that is performed with the hands.",
    "Our hands are our tongues, our bodies are our language.",
    "Deaf culture is a celebration of life, language, and community.",
    "The first permanent school for the deaf in the U.S., now the American School for the Deaf, was founded in 1817.",
    "ASL grammar is completely different from English, with its own rules for phonology, morphology, and syntax.",
    "Gallaudet University, located in Washington, D.C., is the only university in the world specifically for Deaf and hard of hearing students.",
    "Many Deaf people consider themselves part of a cultural and linguistic minority, not as disabled individuals.",
    "A 'name sign' in Deaf culture is a unique sign given to a person, serving as their name within the community."
];

// Facts about JSL and Japanese Deaf Culture
export const JSL_CULTURE_QUOTES: string[] = [
    "Japanese Sign Language is called 日本手話 (Nihon Shuwa).",
    "JSL has its own grammar and syntax, distinct from spoken Japanese.",
    "JSL uses 'yubimoji' (finger letters) to spell out words, especially names and foreign words.",
    "Unlike ASL's one-handed alphabet, JSL's 'yubimoji' sometimes uses both hands for certain characters.",
    "Facial expressions and body movement are crucial grammatical components in JSL.",
    "There are regional dialects and variations within Japanese Sign Language.",
    "The Deaf community in Japan has a rich history and unique cultural identity.",
    "JSL was officially recognized as a language in Japan in 2011.",
    "The Japanese Federation of the Deaf (JFD) is a key organization advocating for the rights of Deaf people in Japan.",
    "In JSL, the direction of a verb's movement can indicate the subject and object of the sentence.",
    "Historically, Deaf education in Japan focused on oralism (lip-reading and speech) before JSL gained more acceptance.",
    "The sign for 'Tokyo' in JSL is based on the shape of the old city gates.",
    "Many JSL signs are based on visual representations of kanji characters."
];

// Facts about Kanji
export const KANJI_CULTURE_QUOTES: string[] = [
    "Kanji are logographic characters from Chinese, introduced to Japan in the 5th century.",
    "There are over 50,000 kanji, but only about 2,136 'jōyō kanji' are for daily use.",
    "Each kanji has readings: 'on'yomi' (Sino-Japanese) and 'kun'yomi' (native Japanese).",
    "The Japan Kanji Aptitude Test (Kanji Kentei) is a popular test of kanji knowledge.",
    "Many kanji are pictographs, derived from pictures, like '木' for tree or '山' for mountain.",
    "Radicals are components of kanji used for classification and dictionary lookup.",
    "The order of strokes for writing a kanji is important and follows specific rules.",
    "Learning kanji is essential for reading most Japanese texts, from newspapers to novels.",
    "Some kanji have many strokes, like '憂鬱' (yūutsu), meaning 'depression', with 29 strokes.",
    "The kanji '愛' (ai) means love and combines radicals for 'receive', 'heart', and 'gracefully walk'."
];